import = ["./iceberg-dark.toml"]

[font.normal]
family = "Iosevka Nerd Font"
style = "Semi Bold"

[font]
size = 15

[window]
opacity = 0.9

[window.dimensions]
columns = 120
lines = 30

[keyboard]
bindings = [
  {key = "C", mods = "Alt", action = "ToggleViMode"},
]
